theme: minima

title: "Kathryn Wu"
tagline: "my journey, rendered in pixels and html"
email: "kathryn.b.wu@gmail.com"
url: "https://kathrynbwu.github.io"
baseurl: "/kathrynwu"

header_pages:
  - projects.md
  - research.md
  - art.md
  - writing.md
