theme: minima

title: "kathryn wu"
email: "kathryn.b.wu@gmail.com"
description: "my journey in pixels and HTML"
url: 
destination: docs

header_pages:
  - projects.md
  - research.md
  - art.md
  - writing.mddestination: docs
